"""sqldim.io — physical data organization utilities.

Provides:
- :class:`ClusteringStrategy` — protocol for row-group ordering (Z-ORDER).
- :class:`SortBasedClustering` — sort-then-write approximation of Z-ORDER.
- :class:`Compactor` — merges small files generated by streaming sinks.
"""

from sqldim.io.clustering import ClusteringStrategy, SortBasedClustering
from sqldim.io.compaction import Compactor

__all__ = [
    "ClusteringStrategy",
    "SortBasedClustering",
    "Compactor",
]
