"""Compactor — merges small Parquet files generated by streaming sinks.

Streaming upserts create many small files over time.  The :class:`Compactor`
reads all files for a table (per partition), sorts by clustering columns,
and rewrites into target-size files — entirely inside DuckDB without any
Python-side data movement.

Usage
-----
.. code-block:: python

    import duckdb
    from sqldim.io import Compactor

    con = duckdb.connect()
    Compactor.compact(
        con=con,
        path="s3://warehouse/bronze/events",
        partition_by=["ingest_date"],
        zorder_by=["source", "customer_id"],
        target_file_size_mb=256,
    )
"""

from __future__ import annotations



def _order_clause(zorder_by: list[str | None]) -> str:
    if not zorder_by:
        return ""
    return " ORDER BY " + ", ".join(zorder_by)


def _partition_clause(partition_by: list[str | None]) -> str:
    if not partition_by:
        return ""
    cols = ", ".join(partition_by)
    return f", PARTITION_BY ({cols})"


def _overwrite_clause(overwrite: bool) -> str:
    return ", OVERWRITE_OR_IGNORE true" if overwrite else ""


class Compactor:
    """Utility for merging small Parquet files via a DuckDB read-sort-rewrite cycle.

    All operations execute entirely inside DuckDB — no Python-side data
    movement, no intermediate files.

    Parameters
    ----------
    (all passed to :meth:`compact` — no stateful constructor)
    """

    @staticmethod
    def compact(
        con,
        path: str,
        *,
        partition_by: list[str | None] = None,
        zorder_by: list[str | None] = None,
        target_file_size_mb: int = 256,
        overwrite: bool = True,
    ) -> int:
        """Read, sort, and rewrite all Parquet files under *path*.

        Parameters
        ----------
        con:
            DuckDB connection.
        path:
            Root directory or URI of the Parquet table
            (e.g. ``"s3://bucket/table"`` or ``"/data/table"``).
        partition_by:
            Hive partition columns.  When provided, the rewrite preserves the
            existing Hive partition layout.
        zorder_by:
            Columns to sort by before writing (Z-ORDER approximation via
            ``ORDER BY``).  ``None`` skips sorting.
        target_file_size_mb:
            Soft target for output file size.  DuckDB does not guarantee
            exact file sizes; this is computed as a row estimate based on
            an average row size heuristic.
        overwrite:
            ``True`` (default) replaces existing files;  ``False`` raises
            if output already exists.

        Returns
        -------
        int
            Number of rows written.
        """
        glob = f"{path.rstrip('/')}/**/*.parquet"

        order_clause = _order_clause(zorder_by)
        partition_clause = _partition_clause(partition_by)
        overwrite_clause = _overwrite_clause(overwrite)

        # Read → sort → rewrite in one DuckDB statement
        sql = (
            f"COPY ("
            f"  SELECT * FROM read_parquet('{glob}', hive_partitioning=TRUE)"
            f"  {order_clause}"
            f") TO '{path}' ("
            f"  FORMAT parquet"
            f"{partition_clause}"
            f"{overwrite_clause}"
            f")"
        )
        con.execute(sql)

        # Count rows in the newly written dataset
        count_sql = (
            f"SELECT count(*) FROM read_parquet('{glob}', hive_partitioning=TRUE)"
        )
        row = con.execute(count_sql).fetchone()
        return int(row[0]) if row else 0
