"""DGM NL Interface — Pydantic output schemas for specialist agents (§11.10).

Five agent output schemas corresponding to the five LLM responsibilities in
§11.2, plus PropRefModel, QueryCandidate, DGMContext, and NLInterfaceState.

All schemas enforce bounded vocabulary at construction time — the DGM
formal types are the Pydantic validation layer (§11.8).
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from pydantic import BaseModel, field_validator, model_validator

from sqldim.core.query.dgm.nl._types import CompositionOp, TemporalIntent
from sqldim.core.query.dgm.nl._types import EntityRegistry

__all__ = [
    "PropRefModel",
    "QueryCandidate",
    "EntityResolutionResult",
    "CandidateRankingResult",
    "TemporalClassificationResult",
    "CompositionalDetectionResult",
    "ExplanationRenderResult",
    "DGMContext",
    "NLInterfaceState",
]


# ---------------------------------------------------------------------------
# Shared value objects
# ---------------------------------------------------------------------------


class PropRefModel(BaseModel):
    """Structured PropRef: node alias + property name (§11.3).

    The alias identifies the node role alias (e.g. ``"c"`` for a customer
    dimension), and ``prop`` is the column name within that node's property
    map P(n).  Together ``alias.prop`` uniquely identifies a measurable
    attribute in the DGM graph.
    """

    alias: str
    prop: str

    def __str__(self) -> str:
        return f"{self.alias}.{self.prop}"


class QueryCandidate(BaseModel):
    """A single valid query candidate from Q_valid(A, B) (§11.5).

    Generated by the recommender from the lattice; the LLM only ranks these
    pre-validated candidates, never introduces new ones (§11.8).
    """

    dag_node_id: int
    description: str
    band_coverage: list[str] = []
    cost_estimate: float = 0.0

    @field_validator("cost_estimate")
    @classmethod
    def _cost_non_negative(cls, v: float) -> float:
        if v < 0:
            raise ValueError(f"cost_estimate must be \u2265 0, got {v}")
        return v


# ---------------------------------------------------------------------------
# §11.2 task 1 — Entity resolution
# ---------------------------------------------------------------------------


class EntityResolutionResult(BaseModel):
    """LLM maps NL terms to PropRef values in P(n) (§11.2 task 1).

    Resolved proprefs all exist in the EntityRegistry closed vocabulary.
    Unresolved terms trigger clarification, not query generation.
    """

    resolved: list[PropRefModel] = []
    unresolved: list[str] = []
    node_aliases: dict[str, str] = {}

    model_config = {"arbitrary_types_allowed": True}

    def model_post_init(self, __context: Any) -> None:  # noqa: ANN401
        object.__setattr__(self, "resolved", list(self.resolved))
        object.__setattr__(self, "unresolved", list(self.unresolved))
        object.__setattr__(self, "node_aliases", dict(self.node_aliases))


# ---------------------------------------------------------------------------
# §11.2 task 2 — Candidate ranking
# ---------------------------------------------------------------------------


class CandidateRankingResult(BaseModel):
    """LLM ranks pre-validated Q_valid candidates by linguistic proximity (§11.2 task 2).

    Candidates arrive pre-validated by the recommender; the LLM only reorders
    them.  Confidence values are in [0, 1]; length must match ``ranked``.
    """

    ranked: list[QueryCandidate]
    confidence: list[float]

    @field_validator("confidence")
    @classmethod
    def _confidence_in_range(cls, v: list[float]) -> list[float]:
        for score in v:
            if not (0.0 <= score <= 1.0):
                raise ValueError(f"confidence score {score!r} not in [0, 1]")
        return v

    @model_validator(mode="after")
    def _lengths_match(self) -> "CandidateRankingResult":
        if len(self.ranked) != len(self.confidence):
            raise ValueError(
                f"ranked length ({len(self.ranked)}) != "
                f"confidence length ({len(self.confidence)})"
            )
        return self


# ---------------------------------------------------------------------------
# §11.2 task 3 — Temporal intent classification
# ---------------------------------------------------------------------------


class TemporalClassificationResult(BaseModel):
    """LLM classifies NL temporal expressions from a closed vocabulary (§11.2 task 3).

    At most one of mode / property_kind / window may be non-None per utterance
    fragment — they are mutually exclusive classification outputs.
    ``confidence`` in [0, 1]; 0.0 when all None (no temporal intent).
    """

    mode: TemporalIntent | None = None
    property_kind: TemporalIntent | None = None
    window: str | None = None  # e.g. "YTD", "ROLLING", "PERIOD"
    confidence: float = 0.0

    @field_validator("confidence")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if not (0.0 <= v <= 1.0):
            raise ValueError(f"confidence {v!r} not in [0, 1]")
        return v

    @model_validator(mode="after")
    def _at_most_one_non_none(self) -> "TemporalClassificationResult":
        non_none = sum(
            v is not None for v in (self.mode, self.property_kind, self.window)
        )
        if non_none > 1:
            raise ValueError(
                "at most one of mode/property_kind/window may be non-None per utterance fragment"
            )
        return self


# ---------------------------------------------------------------------------
# §11.2 task 4 — Compositional intent detection
# ---------------------------------------------------------------------------


class CompositionalDetectionResult(BaseModel):
    """LLM maps multi-question NL to Q_algebra operations (§11.2 task 4).

    JOIN requires a join_key PropRef — omitting it when operation=JOIN is invalid.
    Confidence in [0, 1].
    """

    operation: CompositionOp | None
    join_key: PropRefModel | None
    confidence: float

    @field_validator("confidence")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if not (0.0 <= v <= 1.0):
            raise ValueError(f"confidence {v!r} not in [0, 1]")
        return v

    @model_validator(mode="after")
    def _join_needs_key(self) -> "CompositionalDetectionResult":
        if self.operation is CompositionOp.JOIN and self.join_key is None:
            raise ValueError("JOIN operation requires a join_key PropRef")
        return self


# ---------------------------------------------------------------------------
# §11.2 task 5 — Explanation rendering
# ---------------------------------------------------------------------------


class ExplanationRenderResult(BaseModel):
    """LLM renders the query DAG decomposition in natural language (§11.2 task 5).

    Input is the structured DAG decomposition; this is generation from structured
    input, not from raw schema — prevents hallucination.
    """

    explanation: str
    follow_up_suggestions: list[str]

    @field_validator("explanation")
    @classmethod
    def _explanation_non_empty(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("explanation must not be empty")
        return v


# ---------------------------------------------------------------------------
# §11.10 — DGMContext (dependency injection carrier)
# ---------------------------------------------------------------------------


@dataclass
class DGMContext:
    """Carries DGM runtime state into each Pydantic-AI agent (§11.10).

    Injected via Pydantic-AI's dependency injection mechanism so each agent
    has access to the closed vocabulary and formal structures without globals.

    All optional fields are None when the NL interface runs in classification-
    only mode (no live graph required).
    """

    entity_registry: EntityRegistry
    budget: Any  # ExecutionBudget — typed loosely to avoid circular import
    graph: Any = None  # G — the full DGM graph
    bdd: Any = None  # DGMPredicateBDD
    query_dag: Any = None  # QueryDAG
    recommender: Any = None  # Recommender
    q_current: Any = None  # current lattice position (QueryDAGNode | None)
    con: Any = None  # DuckDB connection for execution node

    @property
    def has_graph(self) -> bool:
        """True when a live DGM graph has been injected."""
        return self.graph is not None


# ---------------------------------------------------------------------------
# §11.10 — NLInterfaceState (LangGraph state model)
# ---------------------------------------------------------------------------


class NLInterfaceState(BaseModel):
    """Persistent state threaded through the LangGraph NL interface (§11.10).

    The checkpointer serialises this between turns — multi-turn conversations
    are handled without additional session management code.
    """

    utterance: str
    entity_result: EntityResolutionResult | None = None
    temporal_result: TemporalClassificationResult | None = None
    compositional: CompositionalDetectionResult | None = None
    candidates: list[QueryCandidate] = []
    ranking_result: CandidateRankingResult | None = None
    q_current: str | None = None  # query DAG node id
    user_selection: int | None = None  # index into ranking_result.ranked
    budget_decision: Any | None = None  # BudgetDecision
    confirmed: bool = False
    want_more_options: bool = False
    partial_result: Any | None = None  # 10% sample for ASYNC budget decision
    result: Any | None = None  # QueryResult
    explanation: str | None = None
    visited_nodes: list[str] = []  # ordered list of graph hops for evals
    node_timings: dict[str, float] = {}  # wall-clock ms per node, keyed by node name

    model_config = {"arbitrary_types_allowed": True}
