"""
Composition & Query — Examples 11 and 12
==========================================

11. Sales star schema — end-to-end SCD pipeline + multi-dimension query
12. Point-in-time price query  ("what were the prices on 2023-12-31?")

The star schema is built entirely from OLTP data generated by
``ProductsSource`` and ``CustomersSource``.  The helper
``_build_star_schema`` runs them through ``LazySCDProcessor`` with
explicit ``as_of`` timestamps to create realistic SCD2 history, then
attaches a synthetic ``fact_sales`` table referencing both historical
and current product surrogate keys.

Run:
    PYTHONPATH=. python -m sqldim.examples.features.composition.showcase
"""
from __future__ import annotations

import os
import random
from datetime import datetime, timezone

import duckdb

from sqldim.processors.scd_engine import NarwhalsSCDProcessor
from sqldim.query.builder import DuckDBDimensionalQuery
from sqldim.sinks import DuckDBSink

from sqldim.examples.datasets.ecommerce import ProductsSource, CustomersSource
from sqldim.examples.utils import make_tmp_db


# ── Star-schema builder ───────────────────────────────────────────────────────

def _sql_to_nw(source, con: duckdb.DuckDBPyConnection):
    """Execute *source* via DuckDB and return the result as a Narwhals DataFrame."""
    import narwhals as nw
    from sqldim.sources import coerce_source
    sql   = coerce_source(source).as_sql(con)
    arrow = con.execute(sql).arrow()
    return nw.from_arrow(arrow, backend="pandas")


def _read_nw(table: str, con: duckdb.DuckDBPyConnection):
    """Read a DuckDB in-memory table and return it as a Narwhals DataFrame."""
    import narwhals as nw
    arrow = con.execute(f"SELECT * FROM {table}").arrow()
    return nw.from_arrow(arrow, backend="pandas")


def _to_pandas(df):
    """Coerce a Narwhals or DuckDB frame to a plain pandas DataFrame."""
    import narwhals as nw
    import pandas as pd
    if isinstance(df, pd.DataFrame):
        return df
    if hasattr(df, "to_pandas"):
        return df.to_pandas()
    return nw.to_native(df)  # pragma: no cover


def _write_back(df, table: str, con: duckdb.DuckDBPyConnection) -> None:
    """Insert rows from *df* into a DuckDB in-memory table, skipping the id column."""
    pd_df = _to_pandas(df)
    cols = [c for c in pd_df.columns if c != "id"]
    con.register("__tmp__", pd_df)
    con.execute(f"INSERT INTO {table}({','.join(cols)}) SELECT {','.join(cols)} FROM __tmp__")
    con.unregister("__tmp__")


# ── Star-schema builder ───────────────────────────────────────────────────────

def _close_scd2_rows(r1, T1, con: duckdb.DuckDBPyConnection) -> None:
    """Close SCD2 rows flagged in *r1.to_close* by setting is_current=False."""
    if r1.to_close is None or len(r1.to_close) == 0:
        return
    to_close_df = _to_pandas(r1.to_close)
    con.register("__to_close__", to_close_df)
    con.execute(f"""
        UPDATE dim_product
        SET    is_current = FALSE, valid_to = '{T1.isoformat()}'
        WHERE  product_id IN (SELECT product_id FROM __to_close__)
          AND  is_current = TRUE
    """)
    con.unregister("__to_close__")


def _build_star_schema(
    prod_src: ProductsSource,
    cust_src: CustomersSource,
    con: duckdb.DuckDBPyConnection,
) -> None:
    """
    Populate ``dim_product``, ``dim_customer``, and ``fact_sales`` in *con*.

    Uses sqldim's ``NarwhalsSCDProcessor`` with explicit ``as_of`` timestamps:

    * T0 = 2023-01-01  → initial OLTP snapshot of products and customers
    * T1 = 2024-01-01  → product change events arrive (price rises + renames)
                         This versions the changed products, creating SCD2 history.

    ``fact_sales`` is then built referencing both the old (2023) and new (2024)
    product surrogate keys so that AS OF queries return different results
    depending on the point-in-time chosen.
    """
    T0 = datetime(2023, 1, 1, tzinfo=timezone.utc)
    T1 = datetime(2024, 1, 1, tzinfo=timezone.utc)

    con.execute("CREATE OR REPLACE SEQUENCE _dim_product_seq START 1")
    con.execute("""
        CREATE OR REPLACE TABLE dim_product (
            id         INTEGER DEFAULT nextval('_dim_product_seq'),
            product_id INTEGER,
            name       VARCHAR,
            category   VARCHAR,
            price      DOUBLE,
            valid_from VARCHAR,
            valid_to   VARCHAR,
            is_current BOOLEAN,
            checksum   VARCHAR
        )
    """)
    con.execute("CREATE OR REPLACE SEQUENCE _dim_customer_seq START 1")
    con.execute("""
        CREATE OR REPLACE TABLE dim_customer (
            id          INTEGER DEFAULT nextval('_dim_customer_seq'),
            customer_id INTEGER,
            full_name   VARCHAR,
            city        VARCHAR,
            valid_from  VARCHAR,
            valid_to    VARCHAR,
            is_current  BOOLEAN,
            checksum    VARCHAR
        )
    """)

    proc = NarwhalsSCDProcessor(natural_key=["product_id"], track_columns=["name", "category", "price"])
    r0 = proc.process(_sql_to_nw(prod_src.snapshot(), con), _read_nw("dim_product", con), as_of=T0)
    _write_back(r0.to_insert, "dim_product", con)

    r1 = proc.process(_sql_to_nw(prod_src.event_batch(1), con), _read_nw("dim_product", con), as_of=T1)
    _close_scd2_rows(r1, T1, con)
    _write_back(r1.to_insert, "dim_product", con)

    cust_proc = NarwhalsSCDProcessor(natural_key=["customer_id"], track_columns=["full_name", "city"])
    cust_snap = _sql_to_nw(cust_src.snapshot(), con).select(["customer_id", "full_name", "city"])
    rc = cust_proc.process(cust_snap, _read_nw("dim_customer", con), as_of=T0)
    _write_back(rc.to_insert, "dim_customer", con)

    con.execute("""
        CREATE OR REPLACE TABLE fact_sales (
            sale_id      INTEGER,
            product_sk   INTEGER,
            customer_sk  INTEGER,
            sale_date    DATE,
            quantity     INTEGER,
            revenue      DOUBLE
        )
    """)

    hist_sks = con.execute("SELECT id FROM dim_product WHERE NOT is_current ORDER BY id").fetchall()
    curr_sks = con.execute("SELECT id FROM dim_product WHERE is_current ORDER BY id").fetchall()
    cust_sks = con.execute("SELECT id FROM dim_customer WHERE is_current ORDER BY id").fetchall()

    if not cust_sks:  # pragma: no cover
        return  # pragma: no cover

    random.seed(77)
    sale_id = 1
    for sk_row in (hist_sks + curr_sks)[:8]:
        sk        = sk_row[0]
        c_sk      = random.choice(cust_sks)[0]
        sale_date = (
            f"2023-{random.randint(6, 11):02d}-15"
            if sk_row in hist_sks
            else f"2024-{random.randint(1, 6):02d}-{random.randint(10, 28)}"
        )
        qty = random.randint(1, 10)
        rev = round(random.uniform(30.0, 400.0), 2)
        con.execute("INSERT INTO fact_sales VALUES (?, ?, ?, ?, ?, ?)", [sale_id, sk, c_sk, sale_date, qty, rev])
        sale_id += 1


# ── Example 11 ────────────────────────────────────────────────────────────────

def example_11_sales_star_schema() -> None:
    """
    End-to-end sqldim demo:

    1. ProductsSource + CustomersSource (OLTP) → sqldim SCD processors → dims
    2. fact_sales built referencing both old and new product SKs
    3. DuckDBDimensionalQuery joins fact to current dimension versions
    """
    print("\n── Example 11: Sales Star Schema (End-to-End Query) ────────────")

    prod_src = ProductsSource(n=6, seed=42)
    cust_src = CustomersSource(n=4, seed=42)
    con      = duckdb.connect()

    _build_star_schema(prod_src, cust_src, con)

    q = (
        DuckDBDimensionalQuery("fact_sales")
        .join_dim("dim_product",  fact_fk="product_sk")
        .join_dim("dim_customer", fact_fk="customer_sk")
        .by("d_dim_product.category", "d_dim_customer.city")
        .sum("f.revenue")
        .count()
    )

    print("  SQL:")
    for line in q.to_sql().splitlines():
        print(f"    {line}")

    rows = q.execute(con)
    print("\n  Results (category × city → revenue, orders):")
    print(f"  {'Category':<14} {'City':<20} {'Revenue':>10}  {'Orders':>6}")
    print(f"  {'-'*14} {'-'*20} {'-'*10}  {'-'*6}")
    for category, city, rev, orders in sorted(r for r in rows if r[0]):
        print(f"  {category:<14} {city:<20} ${rev:>9.2f}  {orders:>6}")

    con.execute("DROP TABLE IF EXISTS dim_product")
    con.execute("DROP TABLE IF EXISTS dim_customer")
    con.execute("DROP SEQUENCE IF EXISTS _dim_product_seq")
    con.execute("DROP SEQUENCE IF EXISTS _dim_customer_seq")
    con.execute("DROP TABLE IF EXISTS fact_sales")
    con.close()


# ── Example 12 ────────────────────────────────────────────────────────────────

def example_12_point_in_time_query() -> None:
    """
    AS OF query — "what were the product prices on 2023-12-31?"

    Because sqldim versioned some products on 2024-01-01, the AS OF clause
    returns their *original* (cheaper) price for the historical view, while
    the current-view query returns the updated prices.
    """
    print("\n── Example 12: Point-in-Time Price Query (AS OF 2023-12-31) ────")

    prod_src = ProductsSource(n=6, seed=42)
    cust_src = CustomersSource(n=4, seed=42)
    con      = duckdb.connect()

    _build_star_schema(prod_src, cust_src, con)

    pit_date = "2023-12-31"

    q_pit = (
        DuckDBDimensionalQuery("fact_sales")
        .join_dim("dim_product", fact_fk="product_sk")
        .by("d_dim_product.product_id", "d_dim_product.name", "d_dim_product.price")
        .sum("f.revenue")
        .as_of(pit_date)
    )
    q_now = (
        DuckDBDimensionalQuery("fact_sales")
        .join_dim("dim_product", fact_fk="product_sk")
        .by("d_dim_product.product_id", "d_dim_product.name", "d_dim_product.price")
        .sum("f.revenue")
    )

    rows_pit = q_pit.execute(con)
    rows_now = q_now.execute(con)

    def sorted_rows(rows):
        return sorted((r for r in rows if r[0] is not None), key=lambda r: r[0])

    print(f"  AS OF {pit_date} (historical prices):")
    for pid, name, price, rev in sorted_rows(rows_pit):
        print(f"    product {pid}  {name:<26}  list=${price:.2f}  revenue=${rev:.2f}")

    print("\n  AS OF today (current prices):")
    for pid, name, price, rev in sorted_rows(rows_now):
        print(f"    product {pid}  {name:<26}  list=${price:.2f}  revenue=${rev:.2f}")

    print(
        "\n  Note: versioned products appear in BOTH views but at different prices."
        "\n        AS OF 2023-12-31 → original price (lower);"
        "\n        current view     → post-update price — correct SCD2 AS OF."
    )

    con.execute("DROP TABLE IF EXISTS dim_product")
    con.execute("DROP TABLE IF EXISTS dim_customer")
    con.execute("DROP SEQUENCE IF EXISTS _dim_product_seq")
    con.execute("DROP SEQUENCE IF EXISTS _dim_customer_seq")
    con.execute("DROP TABLE IF EXISTS fact_sales")
    con.close()


# ── Entry point ───────────────────────────────────────────────────────────────

def run_showcase() -> None:
    """Run the composition showcase: star-schema and point-in-time examples.

    Executes ``example_11_sales_star_schema`` and
    ``example_12_point_in_time_query`` in sequence using a DuckDB in-memory
    database to demonstrate dimensional composition patterns.
    """
    print("============================")
    example_11_sales_star_schema()
    example_12_point_in_time_query()
    print("\nDone.\n")


if __name__ == "__main__":  # pragma: no cover
    run_showcase()
