"""
sqldim Showcase: E-Commerce Order Intelligence Pipeline
-------------------------------------------------------
Pillar 1: SCD Type 2 — Customer loyalty tier history
Pillar 2: Bridge Table — Multi-campaign product attribution
Pillar 3: Accumulating Snapshot — Order lifecycle milestones
Pillar 4: Migration Context — Detect schema drift in live DB
"""

import asyncio
from datetime import datetime
from sqlmodel import Session, SQLModel, create_engine, select
from sqlalchemy.pool import StaticPool

from sqldim.application.examples.real_world.ecommerce.models import (
    Customer,
    Product,
    Campaign,
    ProductCampaignBridge,
    OrderFact,
)
from sqldim.application.datasets.domains.ecommerce.dataset import ecommerce_dataset
from sqldim.core.kimball.dimensions.scd.handler import SCDHandler
from sqldim.migrations.context import DimensionalMigrationContext

# Fields generated by the factory that must be dropped before SCD processing
_CUSTOMER_FACTORY_KEYS = frozenset({"customer_id"})
_PRODUCT_FACTORY_KEYS = frozenset({"product_id"})
_ORDER_FACTORY_KEYS = frozenset({"order_id"})


def _strip(row: dict, drop: frozenset) -> dict:
    return {k: v for k, v in row.items() if k not in drop}


def _version_tag(is_current: bool) -> str:
    return "current" if is_current else "expired"


def _order_stage(o: "OrderFact") -> str:
    if o.returned_at:
        return "returned"
    if o.delivered_at:
        return "delivered"
    if o.shipped_at:
        return "shipped"
    if o.paid_at:
        return "paid"
    return "placed"


def _coerce_placed_at(val: object) -> datetime:
    """Parse a placed_at value to datetime, defaulting to 2024-06-01."""
    if isinstance(val, str):
        try:
            return datetime.fromisoformat(val)
        except ValueError:
            return datetime(2024, 6, 1)
    return val if val is not None else datetime(2024, 6, 1)


async def _pillar1_scd_customers(engine) -> None:
    """SCD Type 2 — Customer Loyalty Tier History (dataset factory)."""
    src = ecommerce_dataset["customers"]
    with Session(engine) as session:
        handler = SCDHandler(
            Customer, session, track_columns=["loyalty_tier", "country_code"]
        )
        await handler.process([_strip(r, _CUSTOMER_FACTORY_KEYS) for r in src.initial])
        # Event batch simulates loyalty-tier upgrades
        await handler.process([_strip(r, _CUSTOMER_FACTORY_KEYS) for r in src.events])
        all_versions = session.exec(
            select(Customer).order_by(Customer.email, Customer.valid_from)
        ).all()

    upgraded = sum(not v.is_current for v in all_versions)
    print("✅ Pillar 1: SCD Type 2 — Customer Loyalty Tier History")
    print(f"   Loaded {src.initial.__len__()} customers via CustomersSource factory.")
    print(
        f"   Total version rows in dim_customer: {len(all_versions)} "
        f"({upgraded} expired / upgraded)."
    )
    for v in all_versions:
        print(
            f"     {v.email:<32} tier={v.loyalty_tier:<12} ({_version_tag(v.is_current)})"
        )
    print()


async def _pillar2_bridge_attribution(engine) -> None:
    """Bridge Table — Multi-Campaign Product Attribution (dataset factory)."""
    src = ecommerce_dataset["products"]
    with Session(engine) as session:
        products = [Product(**_strip(r, _PRODUCT_FACTORY_KEYS)) for r in src.initial]
        session.add_all(products)
        # Campaigns stay inline — no factory for campaigns
        c1 = Campaign(
            campaign_code="SUMMER24",
            campaign_name="Summer Sale",
            channel="email",
            budget_usd=5_000.0,
        )
        c2 = Campaign(
            campaign_code="TECH24",
            campaign_name="Tech Deals",
            channel="social",
            budget_usd=8_000.0,
        )
        session.add_all([c1, c2])
        session.commit()

        # Multi-valued attribution: first product appears in both campaigns
        session.add_all(
            [
                ProductCampaignBridge(
                    product_id=products[0].id, campaign_id=c1.id, weight=0.4
                ),
                ProductCampaignBridge(
                    product_id=products[0].id, campaign_id=c2.id, weight=0.6
                ),
                ProductCampaignBridge(
                    product_id=products[1].id, campaign_id=c1.id, weight=1.0
                ),
            ]
        )
        session.commit()
        bridge_rows = session.exec(select(ProductCampaignBridge)).all()
        p0_name, p1_name = products[0].product_name, products[1].product_name

    print("✅ Pillar 2: Bridge Table — Multi-Campaign Product Attribution")
    print(f"   Products: {p0_name}, {p1_name} (from ProductsSource factory)")
    print(
        f"   Bridge rows: {len(bridge_rows)} "
        f"({p0_name[:20]!r} attributed to 2 campaigns)"
    )
    for b in bridge_rows:
        print(
            f"     product_id={b.product_id}  "
            f"campaign_id={b.campaign_id}  weight={b.weight:.1f}"
        )
    print()


async def _pillar3_order_lifecycle(engine) -> None:
    """Accumulating Snapshot — Order Lifecycle Milestones (dataset factory)."""
    src = ecommerce_dataset["orders"]
    with Session(engine) as session:
        orders = []
        for raw in src.initial:
            placed = _coerce_placed_at(raw.get("placed_at"))
            o = OrderFact(
                order_id=raw["order_id"],
                customer_id=raw["customer_id"],
                product_id=raw["product_id"],
                quantity=raw["quantity"],
                unit_price_at_order=raw["unit_price_at_order"],
                placed_at=placed,
            )
            orders.append(o)
        session.add_all(orders)
        session.commit()
        stored = session.exec(select(OrderFact).order_by(OrderFact.order_id)).all()

    print("✅ Pillar 3: Accumulating Snapshot — Order Lifecycle Milestones")
    print(
        f"   {len(stored)} orders tracked across 5 milestone columns "
        f"(OrdersSource factory):"
    )
    for o in stored:
        print(
            f"     {o.order_id}  stage={_order_stage(o):<12}  "
            f"qty={o.quantity}  value=${o.quantity * o.unit_price_at_order:.2f}"
        )
    print()


def _model_view_cols(model) -> str:
    """Return a comma-separated column list for creating an empty DuckDB view."""
    parts = []
    for n, f in model.model_fields.items():
        ann = f.annotation
        duckdb_type = "VARCHAR" if ann in (str, None) else "INTEGER"
        parts.append(
            f"NULL::{duckdb_type} AS {n}" if duckdb_type != "VARCHAR" else f"'' AS {n}"
        )
    return ", ".join(parts)


async def _pillar4_migration_context() -> None:
    """Migration Context — Live Schema Drift Detection."""
    ctx = DimensionalMigrationContext([Customer, Product, Campaign, OrderFact])
    import duckdb as _duckdb

    duck = _duckdb.connect()
    for model in [Customer, Product, Campaign, OrderFact]:
        tname = model.__tablename__
        duck.execute(
            f"CREATE OR REPLACE VIEW {tname} AS "
            f"SELECT {_model_view_cols(model)} WHERE 1=0"
        )
    current_state = ctx.introspect(duck)
    changes = ctx.diff(current_state)
    print("✅ Pillar 4: Live Schema Drift Detection")
    print(
        f"   Registered {len(ctx.models)} models; "
        f"introspected {len(current_state)} tables."
    )
    if changes:  # pragma: no cover
        print(f"   Detected {len(changes)} pending change(s).")
    else:
        print("   No schema drift detected — schema is up to date.")
    duck.close()


EXAMPLE_METADATA = {
    "name": "ecommerce",
    "title": "E-Commerce Order Intelligence",
    "description": "SCD Type 2 customer tiers + bridge attribution + accumulating order milestones",
    "entry_point": "run_ecommerce_showcase",
}


async def run_ecommerce_showcase():
    """End-to-end e-commerce order intelligence showcase.

    Demonstrates SCD Type 2 customer history, bridge table multi-valued
    campaign attribution, accumulating snapshot order milestones, and
    live schema drift detection via :class:`DimensionalMigrationContext`.
    """
    engine = create_engine(
        "sqlite://", connect_args={"check_same_thread": False}, poolclass=StaticPool
    )
    SQLModel.metadata.create_all(engine)
    print("🛒 E-Commerce Order Intelligence Pipeline\n")
    await _pillar1_scd_customers(engine)
    await _pillar2_bridge_attribution(engine)
    await _pillar3_order_lifecycle(engine)
    await _pillar4_migration_context()
    print(
        "\n🚀 E-Commerce Pipeline complete. SCD2 + Bridge + Accumulating + Migrations."
    )
    engine.dispose()


if __name__ == "__main__":  # pragma: no cover
    asyncio.run(run_ecommerce_showcase())
