"""DGM sub-package — Dimensional Graph Model public API.

All symbols that were previously accessible via ``from sqldim.core.query.dgm import X``
continue to work unchanged.  Individual submodule imports are also available::

    from sqldim.core.query.dgm.annotations import AnnotationSigma
    from sqldim.core.query.dgm.bdd import BDDManager
    from sqldim.core.query.dgm.preds import ScalarPred, AND
    ...
"""

# Re-export everything that core.py exposes (all submodule re-exports + DGMQuery)
from sqldim.core.query.dgm.core import (  # noqa: F401
    # Internal helpers accessed by tests
    _collect_fk_matches,
    _has_path_pred,
    _infer_on,
    # TemporalContext + DGMQuery
    TemporalContext,
    DGMQuery,
    Query,
    # refs
    PropRef,
    AggRef,
    WinRef,
    SignatureRef,
    _format_value,
    _paren_if_compound,
    _ConstExpr,
    ArithExpr,
    # preds
    ScalarPred,
    AND,
    OR,
    NOT,
    RawPred,
    Strategy,
    ALL,
    SHORTEST,
    K_SHORTEST,
    MIN_WEIGHT,
    Quantifier,
    VerbHop,
    VerbHopInverse,
    BridgeHop,
    Compose,
    PathPred,
    PathAgg,
    SignaturePred,
    SAFETY,
    LIVENESS,
    RESPONSE,
    PERSISTENCE,
    RECURRENCE,
    SequenceMatch,
    # graph
    GraphAlgorithm,
    NodeAlg,
    PairAlg,
    SubgraphAlg,
    CommAlg,
    LOUVAIN,
    LABEL_PROPAGATION,
    CONNECTED_COMPONENTS,
    TARJAN_SCC,
    PAGE_RANK,
    BETWEENNESS_CENTRALITY,
    CLOSENESS_CENTRALITY,
    DEGREE,
    COMMUNITY_LABEL,
    OUTGOING_SIGNATURES,
    INCOMING_SIGNATURES,
    DOMINANT_OUTGOING_SIGNATURE,
    DOMINANT_INCOMING_SIGNATURE,
    SIGNATURE_DIVERSITY,
    SHORTEST_PATH_LENGTH,
    MIN_WEIGHT_PATH_LENGTH,
    REACHABLE,
    DISTINCT_SIGNATURES,
    DOMINANT_SIGNATURE,
    SIGNATURE_SIMILARITY,
    MAX_FLOW,
    DENSITY,
    DIAMETER,
    GLOBAL_SIGNATURE_COUNT,
    GLOBAL_DOMINANT_SIGNATURE,
    SIGNATURE_ENTROPY,
    NodeExpr,
    PairExpr,
    SubgraphExpr,
    GraphExpr,
    Endpoint,
    Bound,
    Free,
    FREE,
    RelationshipSubgraph,
    GraphStatistics,
    TrimCriterion,
    REACHABLE_BETWEEN,
    REACHABLE_FROM,
    REACHABLE_TO,
    MIN_DEGREE,
    SINK_FREE,
    SOURCE_FREE,
    TrimJoin,
    # annotations
    GrainKind,
    SCDKind,
    WeightConstraintKind,
    BridgeSemanticsKind,
    RAGGED,
    SchemaAnnotation,
    Conformed,
    Grain,
    SCDType,
    Degenerate,
    RolePlaying,
    ProjectsFrom,
    FactlessFact,
    DerivedFact,
    WeightConstraint,
    BridgeSemantics,
    Hierarchy,
    annotation_kind,
    AnnotationSigma,
    # temporal
    TemporalMode,
    EVENTUALLY,
    GLOBALLY,
    NEXT,
    ONCE,
    PREVIOUSLY,
    UntilMode,
    SinceMode,
    TemporalOrdering,
    BEFORE,
    AFTER,
    CONCURRENT,
    MEETS,
    MET_BY,
    OVERLAPS,
    OVERLAPPED_BY,
    STARTS,
    STARTED_BY,
    DURING,
    CONTAINS,
    FINISHES,
    FINISHED_BY,
    EQUALS,
    UntilOrdering,
    SinceOrdering,
    TemporalWindow,
    ROLLING,
    TRAILING,
    PERIOD,
    YTD,
    QTD,
    MTD,
    TemporalAgg,
    DeltaSpec,
    ADDED_NODES,
    REMOVED_NODES,
    ADDED_EDGES,
    REMOVED_EDGES,
    CHANGED_PROPERTY,
    ROLE_DRIFT,
    DeltaQuery,
    # recommender
    SuggestionKind,
    Suggestion,
    Stage1Result,
    Stage2Result,
    DGMRecommender,
    ENTROPY_THRESHOLD,
    # planner
    QueryTarget,
    SinkTarget,
    PreComputation,
    CostEstimate,
    ExportPlan,
    DGMPlanner,
    SMALL,
    CLOSURE_THRESHOLD,
    SMALL_GRAPH_THRESHOLD,
    DENSE,
    # exporters
    CypherExporter,
    SPARQLExporter,
    DGMJSONExporter,
    DGMYAMLExporter,
)